// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-MvS9xIRaJKE4L4DXcMPsQ0gvd2ycywg',
    appId: '1:553433107570:web:5b03798d6f7e71beb006eb',
    messagingSenderId: '553433107570',
    projectId: 'sunday-a60c0',
    authDomain: 'sunday-a60c0.firebaseapp.com',
    storageBucket: 'sunday-a60c0.appspot.com',
    measurementId: 'G-87HDTBPMH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvORe339AQ6Y2E4_9g6DrkFzUbRDfqLV4',
    appId: '1:553433107570:android:cef1258b38d418c4b006eb',
    messagingSenderId: '553433107570',
    projectId: 'sunday-a60c0',
    storageBucket: 'sunday-a60c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8KHHvJps5ptAvzmRdjGNtPzOh2-U-xw8',
    appId: '1:553433107570:ios:ffec1fd1dcae640db006eb',
    messagingSenderId: '553433107570',
    projectId: 'sunday-a60c0',
    storageBucket: 'sunday-a60c0.appspot.com',
    iosBundleId: 'com.example.pecAuto1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8KHHvJps5ptAvzmRdjGNtPzOh2-U-xw8',
    appId: '1:553433107570:ios:e1aa3d5f3e86ce87b006eb',
    messagingSenderId: '553433107570',
    projectId: 'sunday-a60c0',
    storageBucket: 'sunday-a60c0.appspot.com',
    iosBundleId: 'com.example.pecAuto1.RunnerTests',
  );
}
